language: node_js
node_js:
  - "stable"
branches:
  only:
  - master
  - jekyll
deploy:
  provider: pages
  local_dir: ./_site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: jekyll