language: node_js
node_js:
  - "stable"
branches:
  only:
  - master
  - jekyll
deploy:
  local_dir: _site
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: jekyll